#!/usr/bin/env python3
"""Generate fixed-cell ASCII fonts for Waveshare EPD from Google Fonts TTF files."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from urllib.request import urlopen

from PIL import Image, ImageDraw, ImageFont


ASCII_START = 32
ASCII_END = 126
ASCII_CHARS = [chr(i) for i in range(ASCII_START, ASCII_END + 1)]


@dataclass(frozen=True)
class FontSpec:
    name: str
    output_cpp: str
    source_url: str
    cell_width: int
    cell_height: int
    preferred_pt: int
    min_pt: int = 18


SPECS = [
    FontSpec(
        name="Font48_GoogleSpaceMono",
        output_cpp="font48_google_spacemono.cpp",
        source_url="https://raw.githubusercontent.com/google/fonts/main/ofl/spacemono/SpaceMono-Regular.ttf",
        cell_width=28,
        cell_height=48,
        preferred_pt=41,
    ),
    FontSpec(
        name="Font48_GoogleManrope",
        output_cpp="font48_google_manrope.cpp",
        source_url="https://raw.githubusercontent.com/google/fonts/main/ofl/manrope/Manrope%5Bwght%5D.ttf",
        cell_width=28,
        cell_height=48,
        preferred_pt=40,
    ),
    FontSpec(
        name="Font48_GoogleAnton",
        output_cpp="font48_google_anton.cpp",
        source_url="https://raw.githubusercontent.com/google/fonts/main/ofl/anton/Anton-Regular.ttf",
        cell_width=30,
        cell_height=48,
        preferred_pt=39,
    ),
]


def download_font(cache_dir: Path, url: str) -> Path:
    cache_dir.mkdir(parents=True, exist_ok=True)
    file_name = url.rsplit("/", 1)[-1]
    out_path = cache_dir / file_name
    if out_path.exists() and out_path.stat().st_size > 0:
        return out_path

    with urlopen(url) as response:
        out_path.write_bytes(response.read())
    return out_path


def bbox_size(font: ImageFont.FreeTypeFont, ch: str) -> tuple[int, int, int, int]:
    x0, y0, x1, y1 = font.getbbox(ch)
    return x0, y0, (x1 - x0), (y1 - y0)


def choose_point_size(font_path: Path, spec: FontSpec) -> int:
    for pt in range(spec.preferred_pt, spec.min_pt - 1, -1):
        font = ImageFont.truetype(str(font_path), pt)
        max_w = 0
        max_h = 0
        for ch in ASCII_CHARS:
            _, _, w, h = bbox_size(font, ch)
            max_w = max(max_w, w)
            max_h = max(max_h, h)
        if max_w <= (spec.cell_width - 2) and max_h <= (spec.cell_height - 2):
            return pt
    return spec.min_pt


def glyph_to_row_bytes(font: ImageFont.FreeTypeFont, ch: str, cell_w: int, cell_h: int) -> list[int]:
    image = Image.new("1", (cell_w, cell_h), 0)
    draw = ImageDraw.Draw(image)

    x0, y0, w, h = bbox_size(font, ch)
    draw_x = (cell_w - w) // 2 - x0
    draw_y = (cell_h - h) // 2 - y0
    draw.text((draw_x, draw_y), ch, font=font, fill=1)

    bytes_per_row = (cell_w + 7) // 8
    data: list[int] = []
    px = image.load()

    for y in range(cell_h):
        for byte_i in range(bytes_per_row):
            value = 0
            for bit in range(8):
                x = byte_i * 8 + bit
                if x >= cell_w:
                    continue
                if px[x, y] != 0:
                    value |= 0x80 >> bit
            data.append(value)
    return data


def render_cpp(spec: FontSpec, source_name: str, point_size: int, table: list[int]) -> str:
    bytes_per_row = (spec.cell_width + 7) // 8
    lines: list[str] = []
    lines.append("/**")
    lines.append(" * Auto-generated by tools/generate_google_epd_fonts.py")
    lines.append(f" * Source: {source_name}")
    lines.append(f" * Size: {spec.cell_width}x{spec.cell_height}, point size: {point_size}")
    lines.append(" */")
    lines.append("")
    lines.append('#include "fonts.h"')
    lines.append('#include "epd_pgmspace_compat.h"')
    lines.append("")
    lines.append(f"const uint8_t {spec.name}_Table[] PROGMEM = {{")

    glyph_size = spec.cell_height * bytes_per_row
    for idx, ch in enumerate(ASCII_CHARS):
        start = idx * glyph_size
        end = start + glyph_size
        glyph_data = table[start:end]
        escaped = "\\'" if ch == "'" else ch
        lines.append(f"  // '{escaped}'")
        for row in range(spec.cell_height):
            row_data = glyph_data[row * bytes_per_row : (row + 1) * bytes_per_row]
            byte_list = ", ".join(f"0x{b:02X}" for b in row_data)
            lines.append(f"  {byte_list},")
        lines.append("")

    lines.append("};")
    lines.append("")
    lines.append(f"sFONT {spec.name} = {{")
    lines.append(f"  {spec.name}_Table,")
    lines.append(f"  {spec.cell_width},")
    lines.append(f"  {spec.cell_height},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def generate_one(spec: FontSpec, repo_root: Path) -> Path:
    cache_dir = repo_root / "tools" / "fonts-cache"
    out_dir = repo_root / "epd12in48" / "src"
    out_dir.mkdir(parents=True, exist_ok=True)

    font_path = download_font(cache_dir, spec.source_url)
    pt = choose_point_size(font_path, spec)
    font = ImageFont.truetype(str(font_path), pt)

    table: list[int] = []
    for ch in ASCII_CHARS:
        table.extend(glyph_to_row_bytes(font, ch, spec.cell_width, spec.cell_height))

    content = render_cpp(spec, font_path.name, pt, table)
    out_file = out_dir / spec.output_cpp
    out_file.write_text(content)
    return out_file


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    generated = [generate_one(spec, repo_root) for spec in SPECS]
    for path in generated:
        print(path.relative_to(repo_root))


if __name__ == "__main__":
    main()
